<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week9Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Week9Notes_files/libs/clipboard/clipboard.min.js"></script>
<script src="Week9Notes_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Week9Notes_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Week9Notes_files/libs/quarto-html/popper.min.js"></script>
<script src="Week9Notes_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Week9Notes_files/libs/quarto-html/anchor.min.js"></script>
<link href="Week9Notes_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Week9Notes_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Week9Notes_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Week9Notes_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Week9Notes_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week9Notes</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="modeling-concepts" class="level1">
<h1>Modeling Concepts</h1>
<p>What is a (statistical) model?</p>
<ul>
<li><p>A mathematical representation of some phenomenon on which you’ve observed data</p></li>
<li><p>Form of the model can vary greatly!</p></li>
</ul>
<p><strong>Statistical learning</strong> - Inference, prediction/classification, and pattern finding</p>
<ul>
<li><p>Supervised learning - a variable (or variables) represents an <strong>output</strong> or <strong>response</strong> of interest</p>
<ul>
<li><p>May model response and</p>
<ul>
<li><p>Make <strong>inference</strong> on the model parameters</p></li>
<li><p><strong>predict</strong> a value or <strong>classify</strong> an observation</p></li>
</ul></li>
</ul></li>
</ul>
<p>Our Goal: Understand what it means to be a good predictive model (not make inference)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>bike_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www4.stat.ncsu.edu/~online/datasets/bikeDetails.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1061 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): name, seller_type, owner
dbl (4): selling_price, year, km_driven, ex_showroom_price

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>bike_data <span class="ot">&lt;-</span> bike_data <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_selling_price =</span> <span class="fu">log</span>(selling_price),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">log_km_driven =</span> <span class="fu">log</span>(km_driven)) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(log_km_driven, log_selling_price, <span class="fu">everything</span>())</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>bike_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,061 × 9
   log_km_driven log_selling_price name    selling_price  year seller_type owner
           &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;
 1          5.86             12.1  Royal …        175000  2019 Individual  1st …
 2          8.64             10.7  Honda …         45000  2017 Individual  1st …
 3          9.39             11.9  Royal …        150000  2018 Individual  1st …
 4         10.0              11.1  Yamaha…         65000  2015 Individual  1st …
 5          9.95              9.90 Yamaha…         20000  2011 Individual  2nd …
 6         11.0               9.80 Honda …         18000  2010 Individual  1st …
 7          9.74             11.3  Honda …         78500  2018 Individual  1st …
 8         10.6              12.1  Royal …        180000  2008 Individual  2nd …
 9         10.4              10.3  Hero H…         30000  2010 Individual  1st …
10         10.6              10.8  Bajaj …         50000  2016 Individual  1st …
# ℹ 1,051 more rows
# ℹ 2 more variables: km_driven &lt;dbl&gt;, ex_showroom_price &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SLR line</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike_data, <span class="fu">aes</span>(<span class="at">x =</span> log_km_driven, <span class="at">y =</span> log_selling_price)) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add a squared x term</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike_data, <span class="fu">aes</span>(<span class="at">x =</span> log_km_driven, <span class="at">y =</span> log_selling_price)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add a cubed x term</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike_data, <span class="fu">aes</span>(<span class="at">x =</span> log_km_driven, <span class="at">y =</span> log_selling_price)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># using method = 'gam' (generalized additive model)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike_data, <span class="fu">aes</span>(<span class="at">x =</span> log_km_driven, <span class="at">y =</span> log_selling_price)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tree based model</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># never defined preds, won't run</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike_data, <span class="fu">aes</span>(<span class="at">x =</span> log_km_driven, <span class="at">y =</span> log_selling_price)) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> preds, <span class="fu">aes</span>(<span class="at">x =</span> log_km_driven, <span class="at">y =</span> Tree_Predictions), <span class="at">color =</span> <span class="st">"Blue"</span>,                     <span class="at">linewidth =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="training-a-model" class="level2">
<h2 class="anchored" data-anchor-id="training-a-model">Training a Model</h2>
<p>Once a class of models is chosen, we must define some criteria to fit (or train) the model</p>
<p>Simple Linear Regression (SLR) Model: <span class="math inline">\(E(Y_i | x_i) = \beta_0 + \beta_1 x_i\)</span></p>
<ul>
<li><p>Loss function - Criteria used to fit or train a model</p>
<ul>
<li><p>For a given numeric response value, and prediction,</p>
<ul>
<li><p><span class="math inline">\(y_i - \hat{y_i}\)</span>,</p></li>
<li><p><span class="math inline">\((y_i - \hat{y_i})^2\)</span>,</p></li>
<li><p><span class="math inline">\(|y_i - \hat{y_i}|\)</span></p></li>
</ul></li>
</ul></li>
</ul>
<p>We try to optimize the loss over all the observations used for training</p>
<p><span class="math display">\[\sum_{i=1}^{n} (y_i - \hat{y_i})^2\]</span> <span class="math display">\[\sum_{i=1}^{n} |y_i - \hat{y_i}|\]</span></p>
<section id="fitting-the-slr-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-slr-model">Fitting the SLR Model</h3>
<ul>
<li><p>Often use squared error loss (least squares regression)</p></li>
<li><p>Nice solutions for our estimates exist!</p></li>
</ul>
<p><span class="math display">\[\hat{\beta_0} = \bar{y} + \bar{x} \hat{\beta_1}\]</span></p>
<p><span class="math display">\[\hat{\beta}_1 = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n} (x_i - \bar{x})^2}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> bike_data<span class="sc">$</span>log_selling_price</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> bike_data<span class="sc">$</span>log_km_driven</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>b1_hat <span class="ot">&lt;-</span> <span class="fu">sum</span>((x<span class="sc">-</span><span class="fu">mean</span>(x))<span class="sc">*</span>(y<span class="sc">-</span><span class="fu">mean</span>(y)))<span class="sc">/</span><span class="fu">sum</span>((x<span class="sc">-</span><span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>b0_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)<span class="sc">-</span><span class="fu">mean</span>(x)<span class="sc">*</span>b1_hat</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">round</span>(b0_hat, <span class="dv">4</span>), <span class="fu">round</span>(b1_hat, <span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.6356 -0.3911</code></pre>
</div>
</div>
<p>Now we can find a prediction! Denoted as <span class="math inline">\(\hat{y}\)</span></p>
<ul>
<li><p>Use <code>lm()</code> function to fit in R</p></li>
<li><p>Utilizes <code>formula</code> notation: <code>y ~ x</code> -&gt; <code>response ~ model terms</code></p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>slr_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_selling_price <span class="sc">~</span> log_km_driven, <span class="at">data =</span> bike_data)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>slr_fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_selling_price ~ log_km_driven, data = bike_data)

Coefficients:
  (Intercept)  log_km_driven  
      14.6356        -0.3911  </code></pre>
</div>
</div>
</section>
</section>
<section id="inference-using-slr-model-in-r" class="level2">
<h2 class="anchored" data-anchor-id="inference-using-slr-model-in-r">Inference Using SLR Model in R</h2>
<p>If we assume iid errors that are Normally distributed with the same variance, we can conduct inference!</p>
<ul>
<li><p>Confidence intervals and hypothesis tests around the slope parameter</p></li>
<li><p>Use summary() (generic function!) on our fitted model</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_selling_price ~ log_km_driven, data = bike_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.9271 -0.3822 -0.0337  0.3794  2.5656 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   14.63557    0.18455   79.31   &lt;2e-16 ***
log_km_driven -0.39109    0.01837  -21.29   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5953 on 1059 degrees of freedom
Multiple R-squared:  0.2997,    Adjusted R-squared:  0.299 
F-statistic: 453.2 on 1 and 1059 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>Can use <code>anova()</code> to get Analysis of Variance information</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(slr_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log_selling_price
                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
log_km_driven    1 160.58 160.583  453.19 &lt; 2.2e-16 ***
Residuals     1059 375.24   0.354                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>Residual diagnostics can be found via <code>plot()</code> on the fitted model</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(slr_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-11-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="prediction-using-slr-model-in-r" class="level2">
<h2 class="anchored" data-anchor-id="prediction-using-slr-model-in-r">Prediction Using SLR Model in R</h2>
<ul>
<li><p>Can use the line for prediction with <code>predict()</code>!</p>
<ul>
<li><p>Should supply fitted object and <code>newdata</code></p>
<ul>
<li>An optional data frame in which to look for variables with which to predict. If omitted, the fitted values are used</li>
</ul></li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>predict</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>predict.lm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(slr_fit, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">log_km_driven =</span> <span class="fu">c</span>(<span class="fu">log</span>(<span class="dv">1000</span>), <span class="fu">log</span>(<span class="dv">10000</span>), <span class="fu">log</span>(<span class="dv">100000</span>))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3 
11.93404 11.03353 10.13302 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(slr_fit, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">log_km_driven =</span> <span class="fu">c</span>(<span class="fu">log</span>(<span class="dv">1000</span>), <span class="fu">log</span>(<span class="dv">10000</span>), <span class="fu">log</span>(<span class="dv">100000</span>)))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
152365.60  61915.64  25160.19 </code></pre>
</div>
</div>
</section>
<section id="quantifying-how-well-the-model-predicts" class="level2">
<h2 class="anchored" data-anchor-id="quantifying-how-well-the-model-predicts">Quantifying How Well the Model Predicts</h2>
<p>We use a loss function to fit the model. We use a <strong>metric</strong> to evaluate the model!</p>
<ul>
<li><p>Often use the same loss function for fitting and as the metric</p></li>
<li><p>For a given <strong>numeric</strong> response value, <span class="math inline">\(y_i\)</span>, and prediction, <span class="math inline">\(\hat{y_i}\)</span>,</p></li>
</ul>
<p><span class="math display">\[(y_i - \hat{y_i})^2, |y_i - \hat{y_i}|\]</span></p>
<ul>
<li>Incorporate all points via</li>
</ul>
<p><span class="math display">\[\frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y}_i)^2,\ \frac{1}{n}\sum_{i=1}^{n}\left|y_i-\hat{y}_i\right|\]</span></p>
<section id="metric-function" class="level3">
<h3 class="anchored" data-anchor-id="metric-function">Metric Function</h3>
<ul>
<li>For a numeric response, we commonly use squared error loss as our metric to evaluate a prediction</li>
</ul>
<p><span class="math display">\[L(y_i,\hat{y}_i)=(y_i-\hat{y}_i)^2\]</span></p>
<ul>
<li>Use <strong>Root Mean Square Error</strong> as a metric across all observations</li>
</ul>
<p><span class="math display">\[\mathrm{RMSE}=\sqrt{\frac{1}{n}\sum_{i=1}^{n}L(y_i,\hat{y}_i)}=\sqrt{\frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}\]</span></p>
<section id="commonly-used-metrics" class="level4">
<h4 class="anchored" data-anchor-id="commonly-used-metrics">Commonly Used Metrics</h4>
<p>For prediction (numeric response)</p>
<ul>
<li><p>Mean Squared Error (MSE) or Root Mean Squared Error (RMSE)</p></li>
<li><p>Mean Absolute Error (MAE or MAD - deviation)</p></li>
</ul>
<p><span class="math display">\[L(y_i,\hat{y}_i)=|y_i-\hat{y}_i|\]</span>Huber Loss</p>
<ul>
<li>Doesn’t penalize large mistakes as much as MSE</li>
</ul>
<p>For classification (categorical response)</p>
<ul>
<li><p>Accuracy</p></li>
<li><p>log-loss</p></li>
<li><p>AUC</p></li>
<li><p>F1 Score</p></li>
</ul>
</section>
</section>
<section id="evaluating-our-slr-model" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-our-slr-model">Evaluating our SLR Model</h3>
<p>We could find our metric for our SLR model using the training data</p>
<ul>
<li>Called <strong>training error</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(slr_fit))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
12.34461 11.25681 10.96222 10.70779 10.74337 10.33280 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>((bike_data<span class="sc">$</span>log_selling_price<span class="sc">-</span><span class="fu">predict</span>(slr_fit))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3536708</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((bike_data<span class="sc">$</span>log_selling_price<span class="sc">-</span><span class="fu">predict</span>(slr_fit))<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5947023</code></pre>
</div>
</div>
<p>Doesn’t tell us how well we do on data we haven’t seen!</p>
</section>
</section>
<section id="training-vs-test-sets" class="level2">
<h2 class="anchored" data-anchor-id="training-vs-test-sets">Training vs Test Sets</h2>
<p>Ideally we want our model to predict well for observations it <strong>has yet to see</strong>!</p>
<ul>
<li><p>For <em>multiple</em> linear regression models, our training MSE will always decrease as we add more variables to the model…</p></li>
<li><p>We’ll need an independent test set to predict on (more on this shortly!)</p></li>
</ul>
</section>
<section id="big-picture-modeling" class="level2">
<h2 class="anchored" data-anchor-id="big-picture-modeling">Big Picture Modeling</h2>
<p>Supervised Learning methods try to relate predictors to a response variable through a model</p>
<ul>
<li><p>Lots of common models</p>
<ul>
<li><p>Regression models</p></li>
<li><p>Tree based methods</p></li>
<li><p>Naive Bayes</p></li>
<li><p>k Nearest Neighbors</p></li>
<li><p>…</p></li>
</ul></li>
<li><p>For a set of predictor values, each will produce some prediction we can call <span class="math inline">\(\hat{y}\)</span></p></li>
<li><p>Evaluate model via a metric</p></li>
<li><p>Will use an independent test set or cross-validation to more accurately judge our model</p></li>
</ul>
</section>
</section>
<section id="prediction-trainingtest-sets" class="level1">
<h1>Prediction &amp; Training/Test Sets</h1>
<p>In this course we focus on the <strong>predictive modeling</strong> paradigm. In the end, we’ll often fit different <em>families of models</em> (say some multiple linear regression models, a tree based model, and a random forest model) to a given data set. We’ll then judge those models using some model <em>metric</em> to determine which model is best at predicting!</p>
<p>Let’s break down this process into a few steps.</p>
<section id="predictive-modeling-idea" class="level2">
<h2 class="anchored" data-anchor-id="predictive-modeling-idea">Predictive Modeling Idea</h2>
<p>First we’ll choose a form for a model. The types of models to consider often depends on the subject matter at hand.</p>
<p>Once we’ve chosen a model type, we <strong>fit</strong> the model using some algorithm. Usually, we can write this fitting process in terms of minimizing some <strong>loss</strong> function.</p>
<p>We then need to determine the quality of predictions made by the model. We use a model <strong>metric</strong> to do this. Quite often, the loss function and model metric are the same, but this isn’t always the case!</p>
<p>For numeric response, the most common model metric is mean squared error (MSE) or root mean squared error (RMSE). For a categorical reponse, the most commmon model metrics are accuracy and log-loss (discussed in detail later).</p>
</section>
<section id="training-vs-test-sets-1" class="level2">
<h2 class="anchored" data-anchor-id="training-vs-test-sets-1"><strong>Training vs Test Sets</strong></h2>
<p>Ideally we want our model to predict well for observations <strong>it has yet to see</strong>. We want to avoid <em>overfitting</em> to the data we train our model on.</p>
<p>The evaluation of predictions over the observations used to <em>fit or train the model</em> is called the <strong>training (set) error</strong></p>
<ul>
<li>Let <span class="math inline">\(y_i\)</span> denote an observed value and <span class="math inline">\(\hat{y}_i\)</span> denote our prediction for that observation. If RMSE was our metric,</li>
</ul>
<p><span class="math display">\[\mathrm{Training\ RMSE}=\sqrt{\frac{1}{\#\text{ of observations used to fit the model}}\sum_{\text{observations used to fit the model}}(y_i-\hat{y}_i)^2}\]</span></p>
<ul>
<li>If we only consider this error, we’ll have no idea how the model will fare on data it hasn’t seen!</li>
</ul>
<p>One method to obtain a better idea about model performance is to <em>randomly</em> split the data into a <strong>training set</strong> and <strong>test set</strong>.</p>
<ul>
<li><p>On the training set we can fit (or train) our models</p></li>
<li><p>We can then predict for the test set observations and judge effectiveness with our metric</p></li>
<li><p>We want the training set to have about 80% - 90% of the total data</p></li>
</ul>
<section id="example-of-fitting-and-evaluating-models" class="level3">
<h3 class="anchored" data-anchor-id="example-of-fitting-and-evaluating-models"><strong>Example of Fitting and Evaluating Models</strong></h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>bike_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www4.stat.ncsu.edu/~online/datasets/bikeDetails.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1061 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): name, seller_type, owner
dbl (4): selling_price, year, km_driven, ex_showroom_price

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>bike_data <span class="ot">&lt;-</span> bike_data <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_selling_price =</span> <span class="fu">log</span>(selling_price), </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">log_km_driven =</span> <span class="fu">log</span>(km_driven)) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(log_km_driven, log_selling_price, <span class="fu">everything</span>())</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>bike_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,061 × 9
   log_km_driven log_selling_price name    selling_price  year seller_type owner
           &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;
 1          5.86             12.1  Royal …        175000  2019 Individual  1st …
 2          8.64             10.7  Honda …         45000  2017 Individual  1st …
 3          9.39             11.9  Royal …        150000  2018 Individual  1st …
 4         10.0              11.1  Yamaha…         65000  2015 Individual  1st …
 5          9.95              9.90 Yamaha…         20000  2011 Individual  2nd …
 6         11.0               9.80 Honda …         18000  2010 Individual  1st …
 7          9.74             11.3  Honda …         78500  2018 Individual  1st …
 8         10.6              12.1  Royal …        180000  2008 Individual  2nd …
 9         10.4              10.3  Hero H…         30000  2010 Individual  1st …
10         10.6              10.8  Bajaj …         50000  2016 Individual  1st …
# ℹ 1,051 more rows
# ℹ 2 more variables: km_driven &lt;dbl&gt;, ex_showroom_price &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Here our response variable is the <code>log_selling_price = ln(selling_price)</code>. We could consider the family of multiple linear regression (MLR) models with differing predictors (x variables).</p>
<ul>
<li><p>The basic MLR model with <span class="math inline">\(p\)</span> predictors models the average response variable given the predictors (that’s what <span class="math inline">\(E(Y \mid x_1, x_2, \ldots, x_p)\)</span> represents, the average or expected <span class="math inline">\(Y\)</span>, given (that’s what the vertical bar means) the values of <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(x_p\)</span>) as a linear function (linear in the parameter terms).</p>
<p><span class="math display">\[E(Y \mid x_1, x_2, \ldots, x_p) = \beta_0 + \beta_1x_1 + \beta_2x_2 + \cdots + \beta_px_p\]</span></p></li>
<li><p><span class="math inline">\(\beta_0\)</span> is the intercept and each <span class="math inline">\(\beta_j\)</span> is a slope term associated with a predictor variable.</p></li>
<li><p>As with SLR, we could model the error term with a Normal distribution if we were interested in making inference on the parameters.</p></li>
</ul>
<p>These basic models find coefficients that minimize the sum of squared residuals (i.e.&nbsp;uses squared error loss to fit the model).</p>
<ul>
<li>MLR modeling fitting criterion (the ‘hats’ just imply the parameters are estimates rather than the ‘true’ underlying values):</li>
</ul>
<p><span class="math display">\[\min_{\hat{\beta}\text{'s}} \sum_{i=1}^{n}\left(y_i-\left(\hat{\beta}_0+\hat{\beta}_1x_{1i}+\cdots+\hat{\beta}_px_{pi}\right)\right)^2\]</span></p>
<p>If you are familiar with maximum likelihood, the estimated <span class="math inline">\(\beta\)</span>’s turn out to be equivalent to doing maximum likelihood estimation with the iid error Normal, constant variance, assumption!</p>
<ul>
<li><p>Consider three competing MLR models:</p>
<ul>
<li><p>Model 1: log_selling_price = intercept + slope*year + Error</p></li>
<li><p>Model 2: log_selling_price = intercept + slope*log_km_driven + Error</p></li>
<li><p>Model 3: log_selling_price = intercept + slope*log_km_driven + slope*year + Error</p></li>
</ul></li>
</ul>
<p>We can split the data randomly into a training set and a testing set. There are a lot of ways to do this. We’ll use the <code>rsample::initial_split()</code> function.</p>
<ul>
<li><p>We commonly use an 80/20 or 70/30 training/test split. The proportion used in this split really depends on the amount of data you have and your subject matter expertise. More data in the test set means a better estimate of the model’s performance. However, less data in the training set means a more variable model (bigger changes in predictions from data set to data set).</p></li>
<li><p>Let’s split our <code>bike_data</code> into a training and test set.</p>
<ul>
<li><p>Use <code>initial_split()</code> to create an initial object</p></li>
<li><p>Use <code>training()</code> and <code>testing()</code> on that object to create the two data sets (note the number of observations in each set below!)</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.5.0 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ broom        1.0.13     ✔ rsample      1.3.2 
✔ dials        1.4.4      ✔ tailor       0.1.0 
✔ infer        1.1.0      ✔ tune         2.1.0 
✔ modeldata    1.5.1      ✔ workflows    1.3.0 
✔ parsnip      1.6.0      ✔ workflowsets 1.1.1 
✔ recipes      1.3.3      ✔ yardstick    1.4.0 </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dials' was built under R version 4.6.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">10</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>bike_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(bike_data, <span class="at">prop =</span> <span class="fl">0.7</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>bike_train <span class="ot">&lt;-</span> <span class="fu">training</span>(bike_split)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>bike_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(bike_split)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>bike_train</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 742 × 9
   log_km_driven log_selling_price name    selling_price  year seller_type owner
           &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;
 1         10.8              10.3  Bajaj …         30000  2012 Individual  1st …
 2          8.95             10.6  Honda …         40000  2015 Individual  1st …
 3          9.99              9.80 Bajaj …         18000  2005 Individual  1st …
 4         10.2              10.5  Hero H…         35000  2017 Individual  1st …
 5         10.8              11.4  Royal …         85000  2013 Individual  1st …
 6          9.88             10.3  Bajaj …         30000  2008 Individual  1st …
 7         10.5              10.5  Hero C…         35000  2014 Individual  1st …
 8          9.68              9.90 Bajaj …         20000  2009 Individual  1st …
 9         11.1              10.1  Hero H…         25000  2008 Individual  3rd …
10          8.94             12.2  Bajaj …        200000  2019 Individual  1st …
# ℹ 732 more rows
# ℹ 2 more variables: km_driven &lt;dbl&gt;, ex_showroom_price &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>bike_test</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 319 × 9
   log_km_driven log_selling_price name    selling_price  year seller_type owner
           &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;
 1          8.64             10.7  Honda …         45000  2017 Individual  1st …
 2          9.39             11.9  Royal …        150000  2018 Individual  1st …
 3          7.03             12.8  Yamaha…        365000  2019 Individual  1st …
 4          7.44             12.1  Jawa 42        185000  2020 Individual  1st …
 5         10.9              10.1  Suzuki…         25000  2012 Individual  1st …
 6         11.0               9.62 Hero P…         15000  2008 Individual  1st …
 7          7.60             12.1  Jawa S…        180000  2019 Individual  1st …
 8         10.1              10.6  Honda …         42000  2017 Individual  1st …
 9          9.21              9.95 Hero H…         21000  2009 Individual  1st …
10          9.95             10.7  Hero G…         45000  2018 Individual  1st …
# ℹ 309 more rows
# ℹ 2 more variables: km_driven &lt;dbl&gt;, ex_showroom_price &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We can fit or train these models on the training set. Recall we use <code>lm()</code> to easily fit an MLR model via formula notation. With formula notation we put our response variable on the left and our model for the predictors on the right. The model can include interactions, non-linear terms, etc. If we just want ‘main effects’ we separate predictors with + on the right hand side (we’ll cover this in more detail later!)</p>
<ul>
<li>Let’s fit our three models and save them as objects.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_selling_price <span class="sc">~</span> year, <span class="at">data =</span> bike_train)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(reg1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)          year 
-186.17235057    0.09777273 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_selling_price <span class="sc">~</span> log_km_driven, <span class="at">data =</span> bike_train)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(reg2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) log_km_driven 
   14.6228627    -0.3899342 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_selling_price <span class="sc">~</span> year <span class="sc">+</span> log_km_driven, <span class="at">data =</span> bike_train)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(reg3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)          year log_km_driven 
-131.66741960    0.07191291   -0.24274055 </code></pre>
</div>
</div>
<p>ow we have the fitted models. Want to use them to predict the response</p>
<ul>
<li><p>Model 1: <span class="math inline">\(\widehat{log\_selling\_price} = −186.1724+0.0978*year\)</span></p></li>
<li><p>Model 2: <span class="math inline">\(\widehat{log\_selling\_price} = 14.6229−0.3899*log\_km\_driven\)</span></p></li>
<li><p>Model 3: <span class="math inline">\(\widehat{log\_selling\_price} = -131.6674 + 0.0719*year − 0.2427*log\_km\_driven\)</span></p></li>
</ul>
<p>To get predictions from our model, we use the <code>predict()</code> function and specify the <code>newdata</code> we want to predict for as a data frame with column names matching our predictors in our models. If we don’t specify any <code>newdata</code>, it returns the predictions made on the training data.</p>
<ul>
<li>We can see the first few predictions on the training data from the first model via the code below</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>bike_train <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mod1_preds =</span> <span class="fu">predict</span>(reg1)) <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(log_selling_price, year, mod1_preds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 742 × 3
   log_selling_price  year mod1_preds
               &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
 1             10.3   2012      10.5 
 2             10.6   2015      10.8 
 3              9.80  2005       9.86
 4             10.5   2017      11.0 
 5             11.4   2013      10.6 
 6             10.3   2008      10.2 
 7             10.5   2014      10.7 
 8              9.90  2009      10.3 
 9             10.1   2008      10.2 
10             12.2   2019      11.2 
# ℹ 732 more rows</code></pre>
</div>
</div>
<p>Let’s use RMSE as our metric. Although not how we want to compare our models, we can obtain the <strong>training</strong> RMSE easily with <code>predict()</code>. Let’s code it up ourselves and also use <code>yardstick::rmse_vec()</code> to find it (this is the <code>tidymodels</code> way).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#our own calculation for training RMSE</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((bike_train<span class="sc">$</span>log_selling_price <span class="sc">-</span> <span class="fu">predict</span>(reg1))<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5378694</code></pre>
</div>
</div>
<ul>
<li>Now we can supply the actual responses and the model predictions to <code>yardstick::rmse_vec()</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#using yardstick</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>yardstick<span class="sc">::</span><span class="fu">rmse_vec</span>(bike_train<span class="sc">$</span>log_selling_price, <span class="fu">predict</span>(reg1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5378694</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#second and third models</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co">#using yardstick</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rmse_vec</span>(bike_train<span class="sc">$</span>log_selling_price, <span class="fu">predict</span>(reg2))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5669127</code></pre>
</div>
</div>
<ul>
<li><p>These values represent a measure of quality of prediction by these models (as judged by our metric RMSE).</p></li>
<li><p>This estimate of RMSE for the predictions is too <strong>optimistic</strong> compared to how the model would perform with new data!</p></li>
<li><p>Really, what we want to compare is how the models do on data they weren’t trained on.</p></li>
<li><p>We want to find this type of metric on the test set. That means we want to use the <strong>truth</strong> from the test set (<span class="math inline">\(y_i\)</span> for the test set) and compare that to predictions made for that test set observation (<span class="math inline">\(\hat{y_i}\)</span>).</p></li>
</ul>
<p><span class="math display">\[\mathrm{Test\ Set\ RMSE}=\sqrt{\frac{1}{n_{\text{test}}}\sum_{i=1}^{n_{\text{test}}}(y_i-\hat{y}_i)^2}\]</span> To do this in R we need to tell <code>predict()</code> about the <code>newdata</code> being the test set (<code>bike_test</code>). As this is a data frame with columns for our predictors, we can just pass the entire data frame for ease and <code>predict()</code> uses appropriate/needed columns to find our predictions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#look at a few observations and predictions</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>bike_test <span class="sc">|&gt;</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(log_selling_price, year) <span class="sc">|&gt;</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model_1_preds =</span> <span class="fu">predict</span>(reg1, <span class="at">newdata =</span> bike_test))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 319 × 3
   log_selling_price  year model_1_preds
               &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt;
 1             10.7   2017          11.0
 2             11.9   2018          11.1
 3             12.8   2019          11.2
 4             12.1   2020          11.3
 5             10.1   2012          10.5
 6              9.62  2008          10.2
 7             12.1   2019          11.2
 8             10.6   2017          11.0
 9              9.95  2009          10.3
10             10.7   2018          11.1
# ℹ 309 more rows</code></pre>
</div>
</div>
<ul>
<li>Now let’s find the <strong>test set error</strong> for each model</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co">#obtain the test set RMSE for each model</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rmse_vec</span>(bike_test<span class="sc">$</span>log_selling_price, <span class="fu">predict</span>(reg1, <span class="at">newdata =</span> bike_test))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5746992</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rmse_vec</span>(bike_test<span class="sc">$</span>log_selling_price, <span class="fu">predict</span>(reg2, <span class="at">newdata =</span> bike_test))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6548019</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rmse_vec</span>(bike_test<span class="sc">$</span>log_selling_price, <span class="fu">predict</span>(reg3, <span class="at">newdata =</span> bike_test))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.554596</code></pre>
</div>
</div>
<p>We see that our third model with both <code>year</code> and <code>log_km_driven</code> gives a better (by our metric) set of predictions!</p>
<p>When choosing a model, if the RMSE values were ‘close’, we’d want to consider the interpretability of the model (and perhaps the assumptions required by each model if inference was of interest!)</p>
<ul>
<li>Note: we can do this with <code>yardstick::rmse()</code> rather than <code>yardstick::rmse_vec()</code> if our predictions are in the data frame. <code>rmse()</code> takes in the <code>data</code> as the first argument, the <code>truth</code> column as the second, and the <code>estimate</code> (or predictions) as the third.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#look at a few observations and predictions</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>bike_test <span class="sc">|&gt;</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(log_selling_price, log_km_driven) <span class="sc">|&gt;</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model_1_preds =</span> <span class="fu">predict</span>(reg1, <span class="at">newdata =</span> bike_test)) <span class="sc">|&gt;</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rmse</span>(<span class="at">truth =</span> log_selling_price, <span class="at">estimate =</span> model_1_preds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard       0.575</code></pre>
</div>
</div>
</section>
</section>
<section id="recap" class="level2">
<h2 class="anchored" data-anchor-id="recap">Recap</h2>
<p>We generally need to go through a few steps when training and testing our model(s):</p>
<ul>
<li><p>Choose the form of the model</p></li>
<li><p>Fit the model to the data using some algorithm</p>
<ul>
<li>Usually this can be written as a problem where we minimize some loss function</li>
</ul></li>
<li><p>Evaluate the model using a metric</p>
<ul>
<li>RMSE is a very common for a numeric response</li>
</ul></li>
<li><p>Ideally we want our model to predict well for observations <strong>it has yet to see</strong>!</p></li>
</ul>
</section>
</section>
<section id="cross-validation" class="level1">
<h1>Cross Validation</h1>
<p>We’ve discussed the idea of supervised learning. In this paradigm we have a <strong>response</strong> or <strong>target</strong> variable we are trying to predict.</p>
<ul>
<li><p>We posit some model for the response variable that is a function of our predictor variables.</p></li>
<li><p>We fit that model to data (usually can be seen as minimizing some <em>loss</em> function).</p></li>
<li><p>We judge how well our model does at predicting using some <strong>metric.</strong></p>
<ul>
<li>Usually we evaluate our metric on the test set after doing a training/test split.</li>
</ul></li>
</ul>
<p>Recall our example of fitting an MLR model from the last section of notes. There we first split the data into a training and test set. We fit the model on the training set. Then we looked at the RMSE on the test set to judge how well the models did.</p>
<p><span class="math display">\[\mathrm{RMSE}=\sqrt{\frac{1}{n_{\text{test}}}\sum_{i=1}^{n_{\text{test}}}(y_i-\hat{y}_i)^2}\]</span></p>
<p>where <span class="math inline">\(y_i\)</span> is the actual response from the test set and <span class="math inline">\(\hat{y}_i\)</span> is the prediction for that response value using the model.</p>
<p><strong>Note:</strong> The terms metric and loss function are often used interchangeably. They are slightly different.</p>
<ul>
<li><p><strong>Loss function</strong> is usually referred to as the criteria used to optimize or fit the model.</p>
<ul>
<li><p>For an MLR model we usually fit by minimizing the sum of squared errors (MSE or RMSE equivalently) which is the same as using maximum likelihood under the iid Normal, constant variance, error model.</p></li>
<li><p>In this case, MSE or RMSE would be our loss function</p></li>
</ul></li>
<li><p>Our <strong>metric</strong> is the criteria for evaluating the model. When we have a numeric response, our most common criteria is RMSE! In this case the same as the common loss function for fitting the model.</p></li>
</ul>
<p>We could fit our MLR model using a different loss function (say minimizing the absolute deviations). We could also evaluate our model using a different metric (say the average of the absolute deviations).</p>
<section id="cv-without-a-trainingtest-set-split" class="level2">
<h2 class="anchored" data-anchor-id="cv-without-a-trainingtest-set-split"><strong>CV without a Training/Test Set Split</strong></h2>
<p>Sometimes we don’t have a lot of data so we don’t want to split our data into a training and test set. In this setting, CV is often used by itself to select a final model.</p>
<p>Consider our data set about the selling price of motorcycles:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>bike_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www4.stat.ncsu.edu/~online/datasets/bikeDetails.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1061 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): name, seller_type, owner
dbl (4): selling_price, year, km_driven, ex_showroom_price

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>bike_data <span class="ot">&lt;-</span> bike_data <span class="sc">|&gt;</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_selling_price =</span> <span class="fu">log</span>(selling_price),</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">log_km_driven =</span> <span class="fu">log</span>(km_driven)) <span class="sc">|&gt;</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(log_km_driven, year, log_selling_price, <span class="fu">everything</span>())</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>bike_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,061 × 9
   log_km_driven  year log_selling_price name    selling_price seller_type owner
           &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;
 1          5.86  2019             12.1  Royal …        175000 Individual  1st …
 2          8.64  2017             10.7  Honda …         45000 Individual  1st …
 3          9.39  2018             11.9  Royal …        150000 Individual  1st …
 4         10.0   2015             11.1  Yamaha…         65000 Individual  1st …
 5          9.95  2011              9.90 Yamaha…         20000 Individual  2nd …
 6         11.0   2010              9.80 Honda …         18000 Individual  1st …
 7          9.74  2018             11.3  Honda …         78500 Individual  1st …
 8         10.6   2008             12.1  Royal …        180000 Individual  2nd …
 9         10.4   2010             10.3  Hero H…         30000 Individual  1st …
10         10.6   2016             10.8  Bajaj …         50000 Individual  1st …
# ℹ 1,051 more rows
# ℹ 2 more variables: km_driven &lt;dbl&gt;, ex_showroom_price &lt;dbl&gt;</code></pre>
</div>
</div>
<ul>
<li><p>Let’s consider our three linear regression models for the <code>log_selling_price</code></p>
<ul>
<li><p>Model 1: log_selling_price = intercept + slope*year + Error</p></li>
<li><p>Model 2: log_selling_price = intercept + slope*log_km_driven + Error</p></li>
<li><p>Model 3: log_selling_price = intercept + slope*log_km_driven + slope*year + Error</p></li>
</ul></li>
<li><p>We can use CV error to choose between these models without doing a training/test split.</p></li>
<li><p>We’ll see how to do this within the <code>tidymodels</code> framework shortly. For now, let’s do it by hand so we can make sure we understand the process CV uses!</p></li>
</ul>
<section id="implementing-10-fold-cross-validation-ourselves" class="level3">
<h3 class="anchored" data-anchor-id="implementing-10-fold-cross-validation-ourselves"><strong>Implementing 10 fold Cross-Validation Ourselves</strong></h3>
<p>Let’s start with dividing the data into separate (distinct) folds.</p>
<ol type="1">
<li><p>Split the data into 10 separate folds (subsets)</p>
<ul>
<li>We can do this by randomly reordering our observations and taking the first ten percent to be the first fold, 2nd ten percent to be the second fold, and so on.</li>
</ul></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(bike_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1061</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>size_fold <span class="ot">&lt;-</span> <span class="fu">floor</span>(<span class="fu">nrow</span>(bike_data)<span class="sc">/</span><span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>Each fold, except one, will have 106 observations. There will be an extra observation in this case, we’ll lump that into our last fold.</p></li>
<li><p>Let’s get our folds by using <code>sample()</code> to reorder the indices.</p></li>
<li><p>Then we’ll use a for loop to cycle through the pieces and save the folds in a <code>list</code></p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">8</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>random_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(bike_data), <span class="at">size =</span> <span class="fu">nrow</span>(bike_data), <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="co">#see the random reordering</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(random_indices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 591  12 631 899 867  86</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a list to save our folds in</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co">#now cycle through our random indices vector and take the appropriate observations to each fold</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co">#you may want to set i to 1 and run the arguments to from and to in the seq() function</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="co">#change i to 2 and do the same thing to see how this works</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>){</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (i <span class="sc">&lt;</span> <span class="dv">10</span>) {</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>    fold_index <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> (i<span class="dv">-1</span>)<span class="sc">*</span>size_fold <span class="sc">+</span> <span class="dv">1</span>, <span class="at">to =</span> i<span class="sc">*</span>size_fold, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>    folds[[i]] <span class="ot">&lt;-</span> bike_data[random_indices[fold_index], ]</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> { <span class="co">#for i = 10 we need to have 1 more observation </span></span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a>    fold_index <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> (i<span class="dv">-1</span>)<span class="sc">*</span>size_fold <span class="sc">+</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="fu">length</span>(random_indices), <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>    folds[[i]] <span class="ot">&lt;-</span> bike_data[random_indices[fold_index], ]</span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb80-15"><a href="#cb80-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb80-16"><a href="#cb80-16" aria-hidden="true" tabindex="-1"></a>folds[[<span class="dv">1</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 106 × 9
   log_km_driven  year log_selling_price name    selling_price seller_type owner
           &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;
 1         10.1   2014             10.3  Honda …         30000 Individual  1st …
 2          9.21  2016             10.2  Honda …         28000 Individual  2nd …
 3         11.5   2007              9.21 Hero H…         10000 Individual  1st …
 4         10.7   2015             10.3  Honda …         30000 Individual  2nd …
 5          9.40  2014             11.6  Royal …        110000 Individual  1st …
 6         10.8   2009             10.1  Hero H…         25000 Individual  1st …
 7          9.62  2018             10.5  Hero H…         35000 Individual  1st …
 8         10.3   2016             11.2  Bajaj …         70000 Individual  1st …
 9          9.90  2015             10.8  Yamaha…         50000 Individual  1st …
10          9.71  2017             11.8  KTM 25…        135000 Individual  1st …
# ℹ 96 more rows
# ℹ 2 more variables: km_driven &lt;dbl&gt;, ex_showroom_price &lt;dbl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>folds[[<span class="dv">2</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 106 × 9
   log_km_driven  year log_selling_price name    selling_price seller_type owner
           &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;
 1         10.7   2013             10.2  Bajaj …         28000 Individual  1st …
 2          9.21  2018             10.7  Honda …         46000 Individual  1st …
 3          9.68  2016             11.0  Suzuki…         60000 Individual  1st …
 4          9.38  2017             11.6  Honda …        110000 Individual  1st …
 5          8.92  2018             11.1  Hero S…         65000 Individual  1st …
 6          8.99  2018             11.4  Bajaj …         87000 Individual  1st …
 7         11.0   2010              9.90 Bajaj …         20000 Individual  1st …
 8         10.8   2010              9.90 Hero  …         20000 Individual  1st …
 9          9.85  2016             10.5  TVS Ju…         35000 Individual  1st …
10         10.6   2017             11.0  Bajaj …         60000 Individual  2nd …
# ℹ 96 more rows
# ℹ 2 more variables: km_driven &lt;dbl&gt;, ex_showroom_price &lt;dbl&gt;</code></pre>
</div>
</div>
<ul>
<li><p>Let’s put this process into our own function for splitting our data up!</p></li>
<li><p>This function will take in a data set and a number of folds (<code>num_folds</code>) and returns a list with the folds of the data.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>get_cv_splits <span class="ot">&lt;-</span> <span class="cf">function</span>(data, num_folds){</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#get fold size</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  size_fold <span class="ot">&lt;-</span> <span class="fu">floor</span>(<span class="fu">nrow</span>(data)<span class="sc">/</span>num_folds)</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#get random indices to subset the data with</span></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  random_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data), <span class="at">size =</span> <span class="fu">nrow</span>(data), <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#create a list to save our folds in</span></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>  folds <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#now cycle through our random indices vector and take the appropriate observations to each fold</span></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num_folds){</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (i <span class="sc">&lt;</span> num_folds) {</span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>      fold_index <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> (i<span class="dv">-1</span>)<span class="sc">*</span>size_fold <span class="sc">+</span><span class="dv">1</span>, <span class="at">to =</span> i<span class="sc">*</span>size_fold, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a>      folds[[i]] <span class="ot">&lt;-</span> data[random_indices[fold_index], ]</span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb84-14"><a href="#cb84-14" aria-hidden="true" tabindex="-1"></a>      fold_index <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> (i<span class="dv">-1</span>)<span class="sc">*</span>size_fold <span class="sc">+</span><span class="dv">1</span>, <span class="at">to =</span> <span class="fu">length</span>(random_indices), <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb84-15"><a href="#cb84-15" aria-hidden="true" tabindex="-1"></a>      folds[[i]] <span class="ot">&lt;-</span> data[random_indices[fold_index], ]</span>
<span id="cb84-16"><a href="#cb84-16" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb84-17"><a href="#cb84-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb84-18"><a href="#cb84-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(folds)</span>
<span id="cb84-19"><a href="#cb84-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb84-20"><a href="#cb84-20" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">get_cv_splits</span>(bike_data, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="2" type="1">
<li>Now we can fit the data on nine of the folds and test on the tenth. Then switch which fold is left out and repeat the process. We’ll use MSE rather than RMSE as our metric for now.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#set the test fold number</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>test_number <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="co">#pull out the testing fold</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> folds[[test_number]]</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>test</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 107 × 9
   log_km_driven  year log_selling_price name    selling_price seller_type owner
           &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;
 1         10.3   2015              10.1 Honda …         25000 Individual  1st …
 2         10.4   2016              10.5 Hero H…         35000 Individual  1st …
 3         10.1   2018              11.0 Yamaha…         60000 Individual  1st …
 4         10.4   2013              10.6 Bajaj …         40000 Individual  1st …
 5          7.57  2017              12.0 Mahind…        165000 Individual  1st …
 6          9.90  2019              11.4 TVS Ap…         90000 Individual  1st …
 7          8.52  2017              11.1 Bajaj …         65000 Individual  1st …
 8          9.17  2018              11.5 TVS Ap…         95000 Individual  1st …
 9          8.61  2016              10.5 Hero G…         38000 Dealer      1st …
10         10.1   2015              10.7 Yamaha…         45000 Individual  1st …
# ℹ 97 more rows
# ℹ 2 more variables: km_driven &lt;dbl&gt;, ex_showroom_price &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove the test fold from the list and use the rest as training data</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>train_list <span class="ot">&lt;-</span> folds[<span class="sc">-</span>test_number]</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="co">#note that train is only length 9</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(train_list)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
</div>
<ul>
<li>Recall the <code>purrr:reduce()</code> function. This allows us to iteratively apply a function across an object. Here we’ll use <code>reduce()</code> with <code>rbind()</code> to combine the tibbles saved in the different folds.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co">#combine the other folds into train set</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">reduce</span>(train_list, rbind)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="co">#the other nine folds are now in train</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>train</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 954 × 9
   log_km_driven  year log_selling_price name    selling_price seller_type owner
           &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;
 1         11.2   2012              10.7 Hero H…         45000 Individual  1st …
 2         10.4   2014              10.5 Hero I…         35000 Individual  1st …
 3          9.62  2017              11.8 Bajaj …        138000 Individual  1st …
 4          8.85  2017              11.9 Royal …        150000 Individual  1st …
 5         10.6   2010              10.5 Bajaj …         35000 Individual  1st …
 6          8.85  2018              11.2 Honda …         70000 Individual  1st …
 7          8.07  2019              11.4 Hero X…         87000 Individual  1st …
 8          9.80  2017              11.2 Yamaha…         75000 Individual  1st …
 9          9.85  2014              11.5 Honda …        100000 Individual  1st …
10          9.96  2018              11.3 Bajaj …         80000 Individual  1st …
# ℹ 944 more rows
# ℹ 2 more variables: km_driven &lt;dbl&gt;, ex_showroom_price &lt;dbl&gt;</code></pre>
</div>
</div>
<ul>
<li>Now we can fit our model and check the metric on the test set</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_selling_price <span class="sc">~</span> log_km_driven, <span class="at">data =</span> train)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="co">#get test error (MSE - square RMSE)</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>(yardstick<span class="sc">::</span><span class="fu">rmse_vec</span>(test[[<span class="st">"log_selling_price"</span>]], </span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">predict</span>(fit, <span class="at">newdata =</span> test)))<span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3318796</code></pre>
</div>
</div>
<ul>
<li>Ok, let’s wrap that into a function for ease! Let <code>y</code> be a string for the response, <code>x</code> a character <em>vector</em> of predictors, and <code>test_number</code> the fold to test on.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>find_test_metric <span class="ot">&lt;-</span> <span class="cf">function</span>(y, x, folds, test_number){</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#pull out the testing fold</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  test <span class="ot">&lt;-</span> folds[[test_number]]</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#remove the test fold from the list</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>  train_list <span class="ot">&lt;-</span> folds[<span class="sc">-</span>test_number]</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#combine the other folds into train set</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>  train <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">reduce</span>(train_list, rbind)</span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#fit our model. reformulate allows us to take strings and turn that into a formula</span></span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">reformulate</span>(<span class="at">termlabels =</span> x, <span class="at">response =</span> y), <span class="at">data =</span> train)</span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#get test error</span></span>
<span id="cb93-11"><a href="#cb93-11" aria-hidden="true" tabindex="-1"></a>  (yardstick<span class="sc">::</span><span class="fu">rmse_vec</span>(test[[y]], <span class="fu">predict</span>(fit, <span class="at">newdata =</span> test)))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb93-12"><a href="#cb93-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb93-13"><a href="#cb93-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-14"><a href="#cb93-14" aria-hidden="true" tabindex="-1"></a><span class="co">#double check it works</span></span>
<span id="cb93-15"><a href="#cb93-15" aria-hidden="true" tabindex="-1"></a><span class="fu">find_test_metric</span>(<span class="at">y =</span> <span class="st">"log_selling_price"</span>, </span>
<span id="cb93-16"><a href="#cb93-16" aria-hidden="true" tabindex="-1"></a>                 <span class="at">x =</span> <span class="st">"log_km_driven"</span>, </span>
<span id="cb93-17"><a href="#cb93-17" aria-hidden="true" tabindex="-1"></a>                 <span class="at">folds =</span> folds, </span>
<span id="cb93-18"><a href="#cb93-18" aria-hidden="true" tabindex="-1"></a>                 <span class="at">test_number =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3318796</code></pre>
</div>
</div>
<ul>
<li>We can use the <code>purrr::map()</code> function to apply this function to <code>1:10</code>. This will use each fold as the test set once!</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">get_cv_splits</span>(bike_data, <span class="dv">10</span>)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>purrr<span class="sc">::</span><span class="fu">map</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, find_test_metric, </span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> <span class="st">"log_selling_price"</span>, </span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">x =</span> <span class="st">"log_km_driven"</span>, </span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">folds =</span> folds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.2829525

[[2]]
[1] 0.3260931

[[3]]
[1] 0.4689752

[[4]]
[1] 0.3097491

[[5]]
[1] 0.3006277

[[6]]
[1] 0.3152691

[[7]]
[1] 0.4214135

[[8]]
[1] 0.2991941

[[9]]
[1] 0.3496436

[[10]]
[1] 0.4744565</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Now we combine these into one value! We’ll average the MSE values across the folds and then take the square root of that to obtain the RMSE (averaging square roots makes less sense, which is why we found MSE first)!
<ul>
<li>We can again use <code>reduce()</code> to combine all of these values into one number! We average it by dividing by the number of folds and finally find the square root to make it the RMSE!</li>
</ul></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>sum_mse <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, </span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>                      find_test_metric, </span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> <span class="st">"log_selling_price"</span>, </span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">x =</span> <span class="st">"log_km_driven"</span>, </span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">folds =</span> folds) <span class="sc">|&gt;</span></span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>           <span class="fu">reduce</span>(<span class="at">.f =</span> sum)</span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(sum_mse<span class="sc">/</span><span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5956823</code></pre>
</div>
</div>
<ul>
<li>Let’s put it into a function and make it generic for the number of folds we have.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>find_cv <span class="ot">&lt;-</span> <span class="cf">function</span>(y, x, folds, num_folds){</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  sum_mse <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(<span class="dv">1</span><span class="sc">:</span>num_folds, </span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>                        find_test_metric, </span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">y =</span> y, </span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">x =</span>x, </span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">folds =</span> folds) <span class="sc">|&gt;</span></span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">reduce</span>(<span class="at">.f =</span> sum)</span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">sqrt</span>(sum_mse<span class="sc">/</span>num_folds))</span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a><span class="fu">find_cv</span>(<span class="st">"log_selling_price"</span>, <span class="st">"log_km_driven"</span>, folds, <span class="at">num_folds =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5956823</code></pre>
</div>
</div>
</section>
<section id="compare-different-models-using-our-cv-functions" class="level3">
<h3 class="anchored" data-anchor-id="compare-different-models-using-our-cv-functions"><strong>Compare Different Models Using Our CV Functions</strong></h3>
<p>Now let’s compare our three separate models via 10 fold CV! We can use the same <code>folds</code> with different models. This will make our comparisons better (similar to using a block design if you are familiar with that).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">get_cv_splits</span>(bike_data, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol type="1">
<li>First let’s find our CV RMSE on our model with just <code>year</code> as a predictor:</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>cv_reg_1 <span class="ot">&lt;-</span> <span class="fu">find_cv</span>(<span class="st">"log_selling_price"</span>, <span class="st">"year"</span>, folds, <span class="at">num_folds =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="2" type="1">
<li>Now for our model with just <code>log_km_driven</code>:</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>cv_reg_2 <span class="ot">&lt;-</span> <span class="fu">find_cv</span>(<span class="st">"log_selling_price"</span>, <span class="st">"log_km_driven"</span>, folds, <span class="at">num_folds =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="3" type="1">
<li>And for the model with both of these (main) effects:</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>cv_reg_3 <span class="ot">&lt;-</span> <span class="fu">find_cv</span>(<span class="st">"log_selling_price"</span>, <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"log_km_driven"</span>), folds, <span class="at">num_folds =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can then use these CV scores to compare across models and choose the ‘best’ one!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="st">"year"</span> <span class="ot">=</span> cv_reg_1, <span class="st">"log_km_driven"</span> <span class="ot">=</span> cv_reg_2, <span class="st">"both"</span> <span class="ot">=</span> cv_reg_3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         year log_km_driven          both 
    0.5508152     0.5956502     0.5135431 </code></pre>
</div>
</div>
<p>We see that the model that has both predictors has the lowest cross-validation RMSE!</p>
<p><strong>We would now fit this ‘best’ model on the full data set!</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>best_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_selling_price <span class="sc">~</span> year <span class="sc">+</span> log_km_driven, <span class="at">data =</span> bike_data)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>best_fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_selling_price ~ year + log_km_driven, data = bike_data)

Coefficients:
  (Intercept)           year  log_km_driven  
   -148.79329        0.08034       -0.22686  </code></pre>
</div>
</div>
</section>
</section>
<section id="cv-recap" class="level2">
<h2 class="anchored" data-anchor-id="cv-recap"><strong>CV Recap</strong></h2>
<p>Nice! We’ve done a comparison of models on how well they predict on data they are not trained on without splitting our data into a train and test set! This is very useful when we don’t have a lot of data. Again, we would choose our best model (model 3 here) and refit the model on the full data set!</p>
<p>In some cases, we’ll want to use a train/test split and use CV on the training data only so we still have a separate test set for other comparisons. We’ll discuss this idea shortly! We’ll also see how to do this in the <code>tidymodels</code> framework rather than doing it by hand.</p>
</section>
</section>
<section id="multiple-linear-regression" class="level1">
<h1>Multiple Linear Regression</h1>
<section id="fitting-mlr-models" class="level2">
<h2 class="anchored" data-anchor-id="fitting-mlr-models">Fitting MLR Models</h2>
<ul>
<li>Create models with the same slope but intercepts differing by a categorical variable</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>owner_fits <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_selling_price <span class="sc">~</span> owner <span class="sc">+</span> log_km_driven, <span class="at">data =</span> bike_data)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(owner_fits)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) owner2nd owner owner3rd owner owner4th owner  log_km_driven 
   14.62423775    -0.06775874     0.08148045     0.20110313    -0.38930862 </code></pre>
</div>
</div>
<ul>
<li>Create a data frame for plotting</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>x_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(bike_data<span class="sc">$</span>log_km_driven),</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">to =</span> <span class="fu">max</span>(bike_data<span class="sc">$</span>log_km_driven),</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">length =</span> <span class="dv">2</span>)</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>pred_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">log_km_driven =</span> <span class="fu">rep</span>(x_values, <span class="dv">4</span>),</span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">owner =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"1st owner"</span>, <span class="dv">2</span>),</span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">rep</span>(<span class="st">"2nd owner"</span>, <span class="dv">2</span>),</span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">rep</span>(<span class="st">"3rd owner"</span>, <span class="dv">2</span>),</span>
<span id="cb111-8"><a href="#cb111-8" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">rep</span>(<span class="st">"4th owner"</span>, <span class="dv">2</span>)))</span>
<span id="cb111-9"><a href="#cb111-9" aria-hidden="true" tabindex="-1"></a>pred_df <span class="ot">&lt;-</span> pred_df <span class="sc">|&gt;</span></span>
<span id="cb111-10"><a href="#cb111-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predictions =</span> <span class="fu">predict</span>(owner_fits, <span class="at">newdata =</span> pred_df))</span>
<span id="cb111-11"><a href="#cb111-11" aria-hidden="true" tabindex="-1"></a>pred_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  log_km_driven     owner predictions
1      5.857933 1st owner   12.343694
2     13.687677 1st owner    9.295507
3      5.857933 2nd owner   12.275935
4     13.687677 2nd owner    9.227748
5      5.857933 3rd owner   12.425174
6     13.687677 3rd owner    9.376987
7      5.857933 4th owner   12.544797
8     13.687677 4th owner    9.496610</code></pre>
</div>
</div>
<ul>
<li>Plot our different intercept models</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike_data, <span class="fu">aes</span>(<span class="at">x =</span> log_km_driven, <span class="at">y =</span> log_selling_price, <span class="at">color =</span> owner)) <span class="sc">+</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> pred_df, <span class="fu">aes</span>(<span class="at">x =</span> log_km_driven, <span class="at">y =</span> predictions, <span class="at">color =</span> owner))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Create models with the different slopes and intercepts</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>owner_fits_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_selling_price <span class="sc">~</span> owner<span class="sc">*</span>log_km_driven, <span class="at">data =</span> bike_data)</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(owner_fits_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 (Intercept)               owner2nd owner 
                 14.55347484                   0.63862406 
              owner3rd owner               owner4th owner 
                  0.82280649                   2.31991467 
               log_km_driven owner2nd owner:log_km_driven 
                 -0.38219492                  -0.06871037 
owner3rd owner:log_km_driven owner4th owner:log_km_driven 
                 -0.07295150                  -0.19192122 </code></pre>
</div>
</div>
<ul>
<li>Plot our different intercept models</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike_data, <span class="fu">aes</span>(<span class="at">x =</span> log_km_driven, <span class="at">y =</span> log_selling_price, <span class="at">color =</span> owner)) <span class="sc">+</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week9Notes_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Choosing an MLR Model:</p>
<ul>
<li><p>Given a bunch of predictors, tons of models you could fit! How to choose?</p></li>
<li><p>Many variable selection methods exist…</p></li>
<li><p>If you care mainly about prediction, just use cross-validation or training/test split!</p>
<ul>
<li><p>Compare predictions using some metric!</p></li>
<li><p>We’ll see how to use <code>tidymodels</code> to do this in a coherent way shortly!</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="modeling-with-tidymodels" class="level1">
<h1>Modeling with <code>tidymodels</code></h1>
<section id="convert-data" class="level2">
<h2 class="anchored" data-anchor-id="convert-data">Convert Data</h2>
<ul>
<li><p>We saw the use of <code>rsample::initial_split()</code></p>
<ul>
<li>If doing a non-learned transformation, do those first outside of tidymodels</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a>bike_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www4.stat.ncsu.edu/~online/datasets/bikeDetails.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_selling_price =</span> <span class="fu">log</span>(selling_price)) <span class="sc">|&gt;</span></span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>selling_price)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1061 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): name, seller_type, owner
dbl (4): selling_price, year, km_driven, ex_showroom_price

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co">#save creation of new variables for now!</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>bike_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(bike_data, <span class="at">prop =</span> <span class="fl">0.7</span>)</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a>bike_train <span class="ot">&lt;-</span> <span class="fu">training</span>(bike_split)</span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a>bike_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(bike_split)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>initial_split()</code> allows for stratified sampling too!</li>
</ul>
</section>
<section id="data-preparation-with-tidymodels" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation-with-tidymodels">Data Preparation with <code>tidymodels</code></h2>
<p><code>recipes</code> package within <code>tidymodels</code> allows for transformations</p>
<ul>
<li><p>Process keeps track of proper values to use for you!</p></li>
<li><p>Start with <code>recipe()</code> call</p>
<ul>
<li><p>Denote formula for response/predictors and data to use</p></li>
<li><p><code>summary()</code> describes current setup (we don’t want all of these as predictors)</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe</span>(log_selling_price <span class="sc">~</span> ., <span class="at">data =</span> bike_train) <span class="sc">|&gt;</span></span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 4
  variable          type      role      source  
  &lt;chr&gt;             &lt;list&gt;    &lt;chr&gt;     &lt;chr&gt;   
1 name              &lt;chr [3]&gt; predictor original
2 year              &lt;chr [2]&gt; predictor original
3 seller_type       &lt;chr [3]&gt; predictor original
4 owner             &lt;chr [3]&gt; predictor original
5 km_driven         &lt;chr [2]&gt; predictor original
6 ex_showroom_price &lt;chr [2]&gt; predictor original
7 log_selling_price &lt;chr [2]&gt; outcome   original</code></pre>
</div>
</div>
<ul>
<li><p><code>update_role()</code> allows you to declare types of variables (such as ID)</p></li>
<li><p>This keeps the variable around even when not used in a model</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe</span>(log_selling_price <span class="sc">~</span> ., <span class="at">data =</span> bike_train) <span class="sc">|&gt;</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">update_role</span>(name, <span class="at">new_role =</span> <span class="st">"ID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 4
  variable          type      role      source  
  &lt;chr&gt;             &lt;list&gt;    &lt;chr&gt;     &lt;chr&gt;   
1 name              &lt;chr [3]&gt; ID        original
2 year              &lt;chr [2]&gt; predictor original
3 seller_type       &lt;chr [3]&gt; predictor original
4 owner             &lt;chr [3]&gt; predictor original
5 km_driven         &lt;chr [2]&gt; predictor original
6 ex_showroom_price &lt;chr [2]&gt; predictor original
7 log_selling_price &lt;chr [2]&gt; outcome   original</code></pre>
</div>
</div>
<section id="now-add-transformation-steps" class="level3">
<h3 class="anchored" data-anchor-id="now-add-transformation-steps">Now Add Transformation Steps</h3>
<p>Many <code>step_*</code> functions to consider</p>
<ul>
<li><p><code>step_log()</code> to create our <code>log_km_driven</code> variable</p></li>
<li><p><code>step_rm()</code> to remove a variable</p></li>
<li><p><code>step_dummy()</code> to create dummy values for categorical variables</p></li>
<li><p><code>step_normalize()</code> to center and scale numeric predictors</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe</span>(log_selling_price <span class="sc">~</span> ., <span class="at">data =</span> bike_train) <span class="sc">|&gt;</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">update_role</span>(name, <span class="at">new_role =</span> <span class="st">"ID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_log</span>(km_driven) <span class="sc">|&gt;</span></span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_rm</span>(ex_showroom_price) <span class="sc">|&gt;</span><span class="co">#too many nas</span></span>
<span id="cb125-5"><a href="#cb125-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_dummy</span>(owner, seller_type) <span class="sc">|&gt;</span></span>
<span id="cb125-6"><a href="#cb125-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_normalize</span>(<span class="fu">all_numeric</span>(), <span class="sc">-</span><span class="fu">all_outcomes</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Recipe ──────────────────────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Inputs </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of variables by role</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>outcome:   1
predictor: 5
ID:        1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Operations </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Log transformation on: km_driven</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Variables removed: ex_showroom_price</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Dummy variables from: owner seller_type</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Centering and scaling for: all_numeric() -all_outcomes()</code></pre>
</div>
</div>
</section>
</section>
<section id="prep-bake-the-recipe" class="level2">
<h2 class="anchored" data-anchor-id="prep-bake-the-recipe"><code>prep()</code> &amp; <code>bake()</code> the Recipe</h2>
<ul>
<li><p>If you have at least one preprocessing operation, <code>prep()</code> ‘estimates the required parameters from a training set that can be later applied to other data sets’</p></li>
<li><p><code>bake()</code> applies the computations to data</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe</span>(log_selling_price <span class="sc">~</span> ., <span class="at">data =</span> bike_train) <span class="sc">|&gt;</span></span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">update_role</span>(name, <span class="at">new_role =</span> <span class="st">"ID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_log</span>(km_driven) <span class="sc">|&gt;</span></span>
<span id="cb138-4"><a href="#cb138-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(ex_showroom_price) <span class="sc">|&gt;</span></span>
<span id="cb138-5"><a href="#cb138-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(owner, seller_type) <span class="sc">|&gt;</span></span>
<span id="cb138-6"><a href="#cb138-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric</span>(), <span class="sc">-</span><span class="fu">all_outcomes</span>()) <span class="sc">|&gt;</span></span>
<span id="cb138-7"><a href="#cb138-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prep</span>(<span class="at">training =</span> bike_train) <span class="sc">|&gt;</span></span>
<span id="cb138-8"><a href="#cb138-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bake</span>(bike_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 742 × 8
   name       year km_driven log_selling_price owner_X2nd.owner owner_X3rd.owner
   &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;             &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
 1 Bajaj …  1.17    -1.77                11.2            -0.357          -0.0902
 2 Bajaj … -1.36    -0.186                9.39           -0.357          -0.0902
 3 Bajaj … -0.896    0.899               10.2            -0.357          -0.0902
 4 Yamaha…  0.940   -1.24                11.7            -0.357          -0.0902
 5 Royal … -2.96    -1.64                11.0             2.80           -0.0902
 6 Yamaha…  0.940   -0.934               11.4            -0.357          -0.0902
 7 Bajaj …  0.251    0.851               11.0            -0.357          -0.0902
 8 Bajaj …  0.710    0.572               10.9            -0.357          11.1   
 9 Yamaha… -0.667   -0.00575              9.90            2.80           -0.0902
10 Hero X…  0.0220   0.970               10.7            -0.357          -0.0902
# ℹ 732 more rows
# ℹ 2 more variables: owner_X4th.owner &lt;dbl&gt;, seller_type_Individual &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="creating-a-model-with-tidymodels" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-model-with-tidymodels">Creating a Model with <code>tidymodels</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">translate</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression Model Specification (regression)

Computational engine: lm 

Model fit template:
stats::lm(formula = missing_arg(), data = missing_arg(), weights = missing_arg())</code></pre>
</div>
</div>
<p>Set up our model and recipes</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a>bike_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(log_selling_price <span class="sc">~</span> ., <span class="at">data =</span> bike_train) <span class="sc">|&gt;</span></span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">update_role</span>(name, <span class="at">new_role =</span> <span class="st">"ID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_log</span>(km_driven) <span class="sc">|&gt;</span></span>
<span id="cb142-4"><a href="#cb142-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_rm</span>(ex_showroom_price) <span class="sc">|&gt;</span></span>
<span id="cb142-5"><a href="#cb142-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_dummy</span>(owner, seller_type) <span class="sc">|&gt;</span></span>
<span id="cb142-6"><a href="#cb142-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_normalize</span>(<span class="fu">all_numeric</span>(), <span class="sc">-</span><span class="fu">all_outcomes</span>())</span>
<span id="cb142-7"><a href="#cb142-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-8"><a href="#cb142-8" aria-hidden="true" tabindex="-1"></a>bike_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb142-9"><a href="#cb142-9" aria-hidden="true" tabindex="-1"></a> <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="workflows-with-tidymodels" class="level2">
<h2 class="anchored" data-anchor-id="workflows-with-tidymodels"><code>workflow()</code>s with <code>tidymodels</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>bike_wfl <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">add_recipe</span>(bike_rec) <span class="sc">|&gt;</span></span>
<span id="cb143-3"><a href="#cb143-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">add_model</span>(bike_mod)</span>
<span id="cb143-4"><a href="#cb143-4" aria-hidden="true" tabindex="-1"></a>bike_wfl</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow ════════════════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: linear_reg()

── Preprocessor ────────────────────────────────────────────────────────────────
4 Recipe Steps

• step_log()
• step_rm()
• step_dummy()
• step_normalize()

── Model ───────────────────────────────────────────────────────────────────────
Linear Regression Model Specification (regression)

Computational engine: lm </code></pre>
</div>
</div>
</section>
<section id="fit-that-model" class="level2">
<h2 class="anchored" data-anchor-id="fit-that-model"><code>fit()</code> That Model!</h2>
<p>allows us to fit our model to a data set!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>bike_fit <span class="ot">&lt;-</span> bike_wfl <span class="sc">|&gt;</span></span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">fit</span>(bike_train)</span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a>bike_fit <span class="sc">|&gt;</span></span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">tidy</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 5
  term                   estimate std.error statistic  p.value
  &lt;chr&gt;                     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)             10.7       0.0185   581.    0       
2 year                     0.366     0.0217    16.9   1.74e-54
3 km_driven               -0.230     0.0213   -10.8   2.71e-25
4 owner_X2nd.owner         0.0252    0.0188     1.34  1.80e- 1
5 owner_X3rd.owner         0.0414    0.0186     2.23  2.64e- 2
6 owner_X4th.owner         0.0403    0.0186     2.17  3.07e- 2
7 seller_type_Individual  -0.0117    0.0185    -0.635 5.26e- 1</code></pre>
</div>
</div>
</section>
<section id="find-test-set-metrics" class="level2">
<h2 class="anchored" data-anchor-id="find-test-set-metrics">Find Test Set Metric(s)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>bike_wfl <span class="sc">|&gt;</span></span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">last_fit</span>(bike_split) <span class="sc">|&gt;</span></span>
<span id="cb147-3"><a href="#cb147-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">collect_metrics</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  .metric .estimator .estimate .config        
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard       0.521 pre0_mod0_post0
2 rsq     standard       0.439 pre0_mod0_post0</code></pre>
</div>
</div>
<p><strong>The same transformations from the training set are used on the test set!</strong></p>
</section>
<section id="fitting-the-model-with-cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model-with-cross-validation">Fitting the Model with Cross-Validation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a>bike_10_fold <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(bike_train, <span class="dv">10</span>)</span>
<span id="cb149-2"><a href="#cb149-2" aria-hidden="true" tabindex="-1"></a>bike_CV_fits <span class="ot">&lt;-</span> bike_wfl <span class="sc">|&gt;</span></span>
<span id="cb149-3"><a href="#cb149-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">fit_resamples</span>(bike_10_fold)</span>
<span id="cb149-4"><a href="#cb149-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-5"><a href="#cb149-5" aria-hidden="true" tabindex="-1"></a>bike_CV_fits</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Resampling results
# 10-fold cross-validation 
# A tibble: 10 × 4
   splits           id     .metrics         .notes          
   &lt;list&gt;           &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;          
 1 &lt;split [667/75]&gt; Fold01 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 2 &lt;split [667/75]&gt; Fold02 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 3 &lt;split [668/74]&gt; Fold03 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 4 &lt;split [668/74]&gt; Fold04 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 5 &lt;split [668/74]&gt; Fold05 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 6 &lt;split [668/74]&gt; Fold06 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 7 &lt;split [668/74]&gt; Fold07 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 8 &lt;split [668/74]&gt; Fold08 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 9 &lt;split [668/74]&gt; Fold09 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
10 &lt;split [668/74]&gt; Fold10 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;</code></pre>
</div>
</div>
<p>Combine the metrics using <code>collect_metrics()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a>bike_CV_fits <span class="sc">|&gt;</span></span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">collect_metrics</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator  mean     n std_err .config        
  &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard   0.513    10  0.0198 pre0_mod0_post0
2 rsq     standard   0.485    10  0.0395 pre0_mod0_post0</code></pre>
</div>
</div>
<p>This is our CV error on the training set!</p>
</section>
<section id="fit-another-model-with-cross-validation-for-comparison" class="level2">
<h2 class="anchored" data-anchor-id="fit-another-model-with-cross-validation-for-comparison">Fit another Model with Cross-Validation for Comparison</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>bike_int_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(log_selling_price <span class="sc">~</span> ., <span class="at">data =</span> bike_train) <span class="sc">|&gt;</span></span>
<span id="cb153-2"><a href="#cb153-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">update_role</span>(name, <span class="at">new_role =</span> <span class="st">"ID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb153-3"><a href="#cb153-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_log</span>(km_driven) <span class="sc">|&gt;</span></span>
<span id="cb153-4"><a href="#cb153-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_rm</span>(ex_showroom_price) <span class="sc">|&gt;</span></span>
<span id="cb153-5"><a href="#cb153-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_dummy</span>(owner, seller_type) <span class="sc">|&gt;</span></span>
<span id="cb153-6"><a href="#cb153-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_normalize</span>(<span class="fu">all_numeric</span>(), <span class="sc">-</span><span class="fu">all_outcomes</span>()) <span class="sc">|&gt;</span></span>
<span id="cb153-7"><a href="#cb153-7" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_interact</span>(<span class="at">terms =</span> <span class="sc">~</span>km_driven<span class="sc">*</span>year<span class="sc">*</span><span class="fu">starts_with</span>(<span class="st">"seller_type"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Fit the model to the resamples and see our metric</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb154"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a>bike_int_CV_fits <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb154-2"><a href="#cb154-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">add_recipe</span>(bike_int_rec) <span class="sc">|&gt;</span></span>
<span id="cb154-3"><a href="#cb154-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">add_model</span>(bike_mod) <span class="sc">|&gt;</span></span>
<span id="cb154-4"><a href="#cb154-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">fit_resamples</span>(bike_10_fold)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>→ A | warning: prediction from rank-deficient fit; consider predict(., rankdeficient="NA")</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(bike_CV_fits <span class="sc">|&gt;</span> <span class="fu">collect_metrics</span>(),</span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a> bike_int_CV_fits <span class="sc">|&gt;</span> <span class="fu">collect_metrics</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  .metric .estimator  mean     n std_err .config        
  &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard   0.513    10  0.0198 pre0_mod0_post0
2 rsq     standard   0.485    10  0.0395 pre0_mod0_post0
3 rmse    standard   0.535    10  0.0222 pre0_mod0_post0
4 rsq     standard   0.452    10  0.0409 pre0_mod0_post0</code></pre>
</div>
</div>
<ul>
<li><p>Simpler model is better here</p></li>
<li><p>Could now compare its perofrmance on the test set to some other ‘best’ models</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>