---
title: "R Objects, Workflow, and Functions"
format: html
editor: visual
editor_options: 
  chunk_output_type: inline
---

# Vectors 

Create a vector

```{r}
set.seed(42)
my_unif <- runif(30)
is.vector(my_unif)
```


Subset that object

```{r}
my_unif[1:10]
my_unif[c(1:3, 15:17)]
```



Sort the vector

```{r}
sort(my_unif)
```


Create a vector with strings

```{r}
charVec <- c('aaf', 'Adf', 'fgh', 'hgf')
sort(charVec)
```



# Data Frames

- columns with the same type of data

```{r}
data(trees)
head(trees)
```

Subset a column

```{r}
trees$Girth
```


Get attributes from the data frame

```{r}
attributes(trees)
names(trees)
colnames(trees)[2:3]
```


# Lists 

Investigating data frame

```{r}
is.list(trees)
is.data.frame(trees)
```


Can subset as a list

```{r}
trees[1:2]
trees[[2]]
```


Look at linear model fit

```{r}
fit <- lm(Volume ~ Height + Girth, data = trees)
```



Look at structure but restrict info

```{r}
str(fit, max.level = 1)
```


Some helpful functions exist

```{r}
fit$coefficients
coef(fit)
fit$residuals
resid(fit)

fit$rank
#rank(fit) does not work
```


```{r}

```




